"""Remove elements matching exact and partial selectors."""

from __future__ import annotations

import re

from bs4 import Tag

from markitai.webextract.constants import (
    EXACT_SELECTORS,
    EXACT_SELECTORS_JOINED,
    FOOTNOTE_LIST_SELECTORS,
    PARTIAL_SELECTOR_ANCHORED_REGEX,
    PARTIAL_SELECTOR_REGEX,
    TEST_ATTRIBUTES,
)

_ID_DELIMITER_RE = re.compile(r"[\s_\-:.]")
_HEADING_NAMES = frozenset({"h1", "h2", "h3", "h4", "h5", "h6"})


def remove_by_selectors(
    root: Tag,
    main_content: Tag | None,
    *,
    use_partial: bool = True,
) -> int:
    """Remove elements matching known non-content selectors.

    Args:
        root: Content root element.
        main_content: Main content element (protected from removal).
        use_partial: Whether to also use partial attribute matching.

    Returns:
        Number of elements removed.
    """
    to_remove: list[Tag] = []
    seen_ids: set[int] = set()

    # Phase 1: Exact CSS selectors (single joined query for performance)
    try:
        for el in root.select(EXACT_SELECTORS_JOINED):
            eid = id(el)
            if eid in seen_ids:
                continue
            if _should_protect(el, main_content):
                continue
            to_remove.append(el)
            seen_ids.add(eid)
    except Exception:  # noqa: BLE001
        # Fallback: query individually if joined selector fails
        for selector in EXACT_SELECTORS:
            try:
                for el in root.select(selector):
                    eid = id(el)
                    if eid in seen_ids:
                        continue
                    if _should_protect(el, main_content):
                        continue
                    to_remove.append(el)
                    seen_ids.add(eid)
            except Exception:  # noqa: BLE001
                continue

    # Phase 2: Partial attribute matching
    if use_partial:
        for el in root.find_all(True):
            eid = id(el)
            if eid in seen_ids:
                continue
            if _should_protect(el, main_content):
                continue
            if _matches_partial(el) and not _protected_for_partial(el):
                to_remove.append(el)
                seen_ids.add(eid)

    # Remove in reverse document order to avoid parent-before-child issues
    removed = 0
    decomposed: set[int] = set()
    for el in to_remove:
        eid = id(el)
        if eid in decomposed:
            continue
        # Check if any ancestor was already decomposed
        if any(id(p) in decomposed for p in el.parents if isinstance(p, Tag)):
            continue
        el.decompose()
        decomposed.add(eid)
        removed += 1

    return removed


def _should_protect(el: Tag, main_content: Tag | None) -> bool:
    """Check if an element should be protected from removal."""
    # Protect main content and its ancestors
    if main_content is not None:
        if el is main_content:
            return True
        if _is_ancestor_of(el, main_content):
            return True

    # Protect elements inside <pre> or <code>
    for parent in el.parents:
        if isinstance(parent, Tag) and parent.name in ("pre", "code"):
            return True

    # Protect footnote list containers, their parents/children, and the
    # backref links generated by standardize_footnotes (mirrors defuddle
    # removals/selectors.ts).
    try:
        if el.css.match(FOOTNOTE_LIST_SELECTORS):
            return True
        if el.select_one(FOOTNOTE_LIST_SELECTORS) is not None:
            return True
        parent = el.parent
        if (
            isinstance(parent, Tag)
            and parent.name != "[document]"
            and parent.css.match(FOOTNOTE_LIST_SELECTORS)
        ):
            return True
        classes = el.get("class")
        if (
            isinstance(classes, list)
            and "footnote-backref" in classes
            and el.find_parent(id="footnotes") is not None
        ):
            return True
    except Exception:  # noqa: BLE001
        pass

    # Protect <header> elements that are direct children of article/main/section.
    # The bare "header" selector is intended to remove site-level page headers,
    # not article-level headers that contain the h1 and byline.
    if el.name == "header":
        parent = el.parent
        if isinstance(parent, Tag) and parent.name in ("article", "main", "section"):
            return True

    return False


def _is_ancestor_of(ancestor: Tag, descendant: Tag) -> bool:
    """Check if ancestor contains descendant."""
    return any(parent is ancestor for parent in descendant.parents)


def _protected_for_partial(el: Tag) -> bool:
    """Check if a partial-selector match must be kept anyway.

    Partial selectors are fuzzy; defuddle skips them for code content:
    elements that are — or contain — ``<pre>`` blocks (e.g. a code tab
    group whose class happens to contain "dropdown"), and elements inside
    syntax-highlighting wrappers.
    """
    if el.name in ("pre", "code"):
        return True
    if el.find("pre") is not None:
        return True
    for ancestor in el.parents:
        if not isinstance(ancestor, Tag):
            break
        classes = ancestor.get("class")
        if isinstance(classes, list) and any(
            "language-" in c or "syntax-" in c for c in classes
        ):
            return True
    return False


def _matches_partial(el: Tag) -> bool:
    """Check if element matches any partial selector pattern.

    Follows defuddle's matching rules:

    - class and ``data-*`` test attributes are substring-matched.
    - Headings only check class — their ids are auto-generated slugs and
      their data-testid values (e.g. "article-header") cause false
      positives.
    - A delimited id (e.g. "feedback-form") is substring-matched like
      class, but a delimiter-less id is usually a content anchor of
      concatenated heading words (e.g. "loopsandfeedback") — substring
      matching would wrongly strip it, so it must equal a selector token
      outright.
    """
    attrs = el.attrs
    if not attrs:
        return False
    is_heading = el.name in _HEADING_NAMES

    for attr_name in TEST_ATTRIBUTES:
        if attr_name == "id":
            continue
        if is_heading and attr_name != "class":
            continue
        value = attrs.get(attr_name)
        if value is None:
            continue
        # class is a list in BeautifulSoup
        if isinstance(value, list):
            text = " ".join(value)
        else:
            text = str(value)
        if text and PARTIAL_SELECTOR_REGEX.search(text):
            return True

    if is_heading:
        return False
    id_value = attrs.get("id")
    if isinstance(id_value, str) and id_value:
        if _ID_DELIMITER_RE.search(id_value):
            return bool(PARTIAL_SELECTOR_REGEX.search(id_value))
        return bool(PARTIAL_SELECTOR_ANCHORED_REGEX.match(id_value))
    return False
